sudo: required
services:
  - docker
before_install:
  - docker build -t chary123/react-app -f Dockerfile.dev .
script:
  - docker run -t chary123/react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env : "Docker-env"
  bucker_name: "elasticbeanstalk-us-west-1-765413285100"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"



    #http://docker-env.eba-dmwzajne.us-west-1.elasticbeanstalk.com/+