version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000

  tests:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]

  
